#!/rec/sh

export BOOTRECOVERY=`/rec/recoverytrigger`

# Run charger if and only if no key has been pressed to enter into recovery mode
case $BOOTRECOVERY in
	internal)
		export RECVER=`/rec/getrprop recoveryversion`
		if [ "$RECVER" = "kerneldefault" -o -z $RECVER ]
		then
			/sbin/bootcwm5
		else
			case $RECVER in
        			xRec) /sbin/bootxrec;;
			        CWM4) /sbin/bootcwm4;;
				CWM5) /sbin/bootcwm5;;
			        Menu) /sbin/bootmenu;;
			esac
		fi
	      	;;
        back)   /sbin/bootxrec;;
        voldown) /sbin/bootcwm4;;
	volup) /sbin/bootcwm5;;
        menu)   /sbin/bootmenu;;
	*) 	/system/bin/chargemon;;
esac
